"""Compare trispconv output against spconv golden fixtures.

Fixtures are generated by tests/generate_spconv_goldens.py using the
system-installed spconv with ConvAlgo.Native on CPU.

Tests skip automatically when fixtures are missing (CI / fresh clone without
the generator having been run).
"""
import pytest
import torch
from pathlib import Path

import trispconv.pytorch as spconv
from trispconv.pytorch.indices import generate_strided_indice_pairs

FIXTURE_DIR = Path(__file__).parent / "fixtures"
ATOL = 1e-4
RTOL = 1e-4


def _encode_coords(indices, spatial_shape):
    D, H, W = spatial_shape
    idx = indices.long()
    return idx[:, 0] * (D * H * W) + idx[:, 1] * (H * W) + idx[:, 2] * W + idx[:, 3]


def _sort_by_coord(features, indices, spatial_shape):
    enc = _encode_coords(indices, spatial_shape)
    order = enc.argsort()
    return features[order], indices[order]


def _all_fixtures():
    return sorted(FIXTURE_DIR.glob("spconv_golden_*.pt"))


def pytest_generate_tests(metafunc):
    if "fixture_path" in metafunc.fixturenames:
        paths = _all_fixtures()
        metafunc.parametrize(
            "fixture_path",
            paths,
            ids=[p.stem.replace("spconv_golden_", "") for p in paths],
        )


# ---------------------------------------------------------------------------
# Main comparison test
# ---------------------------------------------------------------------------

def test_vs_spconv_golden(fixture_path):
    if not fixture_path.exists():
        pytest.skip("fixture not found")

    fix = torch.load(fixture_path, map_location="cpu", weights_only=True)
    conv_type    = fix["conv_type"]
    C_in         = fix["C_in"]
    C_out        = fix["C_out"]
    k            = fix["kernel_size"]
    s            = fix["stride"]
    p            = fix["padding"]
    d            = fix["dilation"]
    features     = fix["features"]
    indices      = fix["indices"]
    spatial_shape = fix["spatial_shape"]
    batch_size   = fix["batch_size"]
    weight       = fix["weight"]
    bias_val     = fix["bias"]
    ref_features = fix["out_features"]
    ref_indices  = fix["out_indices"]
    ref_spatial  = fix["out_spatial_shape"]

    use_bias = bias_val is not None

    with torch.no_grad():
        if conv_type == "subm":
            module = spconv.SubMConv3d(C_in, C_out, k, dilation=d, bias=use_bias)
            module.weight.data.copy_(weight)
            if use_bias:
                module.bias.data.copy_(bias_val)
            x = spconv.SparseConvTensor(features, indices, spatial_shape, batch_size)
            y = module(x)
            out_f, out_i = _sort_by_coord(y.features, y.indices, y.spatial_shape)

        elif conv_type == "strided":
            module = spconv.SparseConv3d(C_in, C_out, k, stride=s, padding=p, dilation=d, bias=use_bias)
            module.weight.data.copy_(weight)
            if use_bias:
                module.bias.data.copy_(bias_val)
            x = spconv.SparseConvTensor(features, indices, spatial_shape, batch_size)
            y = module(x)
            out_f, out_i = _sort_by_coord(y.features, y.indices, y.spatial_shape)

        elif conv_type == "inverse":
            # Reconstruct the forward downsample indice_dict using trispconv
            down_features  = fix["down_in_features"]
            down_indices   = fix["down_in_indices"]
            down_weight    = fix["down_weight"]
            down_C_in      = fix["down_C_in"]
            down_C_out     = fix["down_C_out"]

            down_in_spatial_shape = fix["down_in_spatial_shape"]
            down = spconv.SparseConv3d(down_C_in, down_C_out, k, stride=s, padding=p,
                                       bias=False, indice_key="down")
            down.weight.data.copy_(down_weight)
            x_down_in = spconv.SparseConvTensor(down_features, down_indices,
                                                down_in_spatial_shape, batch_size)
            x_down = down(x_down_in)

            # The fixture's "features" are ordered by spconv's output voxel order.
            # Rearrange them to match trispconv's output voxel order so features land
            # on the correct voxels regardless of emission ordering.
            ref_enc = _encode_coords(fix["indices"], list(x_down.spatial_shape))
            tri_enc = _encode_coords(x_down.indices, list(x_down.spatial_shape))
            ref_sorted = ref_enc.argsort()
            tri_sorted = tri_enc.argsort()
            features_sorted = fix["features"][ref_sorted]
            tri_perm = torch.empty(len(tri_sorted), dtype=torch.long)
            tri_perm[tri_sorted] = torch.arange(len(tri_sorted))
            features_for_inv = features_sorted[tri_perm]

            module = spconv.SparseInverseConv3d(C_in, C_out, k, bias=use_bias, indice_key="down")
            module.weight.data.copy_(weight)
            if use_bias:
                module.bias.data.copy_(bias_val)

            x_inv = spconv.SparseConvTensor(
                features_for_inv, x_down.indices, x_down.spatial_shape,
                batch_size, indice_dict=x_down.indice_dict,
            )
            y = module(x_inv)
            out_f, out_i = _sort_by_coord(y.features, y.indices, y.spatial_shape)

        else:
            pytest.fail(f"Unknown conv_type: {conv_type}")

    # Compare active coordinate sets
    assert out_i.shape == ref_indices.shape, \
        f"[{conv_type}] index shape mismatch: got {out_i.shape}, expected {ref_indices.shape}"
    assert torch.equal(out_i, ref_indices), \
        f"[{conv_type}] output coordinates differ from spconv reference"

    # Compare feature values
    assert torch.allclose(out_f, ref_features, atol=ATOL, rtol=RTOL), \
        f"[{conv_type}] max feature diff vs spconv: {(out_f - ref_features).abs().max():.6f}"
